export const questions = [
  {
    questionText: "Что из этого самое вкусное?",
    answerOptions: [
      {
        answerText: "Борщец",
        isLover: true,
        isBoss: false,
        isVirgin: false,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Дорогое вино",
        isLover: false,
        isBoss: false,
        isVirgin: false,
        isGhetto: false,
        isDeath: true,
      },
      {
        answerText: "Пирожные из Вольчека:3",
        isLover: false,
        isBoss: true,
        isVirgin: false,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Прингл",
        isLover: false,
        isBoss: false,
        isVirgin: true,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Зеленый салат",
        isLover: false,
        isBoss: false,
        isVirgin: false,
        isGhetto: true,
        isDeath: false,
      },
    ],
  },
  {
    questionText: "Что из этого самое вкусное?",
    answerOptions: [
      {
        answerText: "Борыфвфывщец",
        isLover: true,
        isBoss: false,
        isVirgin: false,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Дорогвфывфывое вино",
        isLover: false,
        isBoss: false,
        isVirgin: false,
        isGhetto: false,
        isDeath: true,
      },
      {
        answerText: "Пирожнвфывыфые из Вольчека:3",
        isLover: false,
        isBoss: true,
        isVirgin: false,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Привфывыфнгл",
        isLover: false,
        isBoss: false,
        isVirgin: true,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Зеленыфвыфвывый салат",
        isLover: false,
        isBoss: false,
        isVirgin: false,
        isGhetto: true,
        isDeath: false,
      },
    ],
  },
  {
    questionText: "Что из этого самое вкусное?",
    answerOptions: [
      {
        answerText: "Борщец",
        isLover: true,
        isBoss: false,
        isVirgin: false,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Дорогое вино",
        isLover: false,
        isBoss: false,
        isVirgin: false,
        isGhetto: false,
        isDeath: true,
      },
      {
        answerText: "Пирожные из Вольчека:3",
        isLover: false,
        isBoss: true,
        isVirgin: false,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Прингл",
        isLover: false,
        isBoss: false,
        isVirgin: true,
        isGhetto: false,
        isDeath: false,
      },
      {
        answerText: "Зеленый салат",
        isLover: false,
        isBoss: false,
        isVirgin: false,
        isGhetto: true,
        isDeath: false,
      },
    ],
  },
];
